### ISSUE TITLE
Parameters must be able to be forced to be a non-negative integers

### ISSUE THREAD

**Issue by monchin** [Theorell/DepecheR#7]
Hello, I tried `depeche`  with a piece of mass cytometry data, but it didn't goes well.
The output:
```R
As the dataset has less than 100 columns, peak centering is
                    applied.
Set 1 with 10 iterations completed in 47 seconds.
Set 2 with 10 iterations completed in 40 seconds.
The optimization was iterated 20 times.
Error in seq_len(ncol(clusterCentersMultSd)) :
  参数必需能被强制改变成非负整数
此外: Warning message:
In seq_len(ncol(clusterCentersMultSd)) : 只用'length.out'参数里的第一个元素
```
the first  Error Chinese line means: `Parameters must be able to be forced to be a non-negative integers`
the last Warning Chinese line: `Only use the first element of parameter 'length.out'`

I guess there is something wrong in `clusterCentersMultSd`, but I don't know how to check.
I pre-transformed data by `asinh`. Should I use other transforming method?

**Comment by jtheorell** [comment]
Dear @monchin, 
Before going into any reproducible examples etc, I have to ask: have you specifically included the mass cytometry parameters that you are interested in, and added it in a matrix/dataframe format, with the parameters as columns and the observations as rows? It could be that this is caused by inclusion of a time parameter, or something else that is not in integer or float format. You should only include the parameters that contain some meaningful information that you think will separate the data, in most instances only the channels with protein abundance information. It seems correct with the transformation. With asinh you should use a co-factor of something like 5 with mass cytometry data, if I am not mistaken. 
Best regards
Jakob

**Comment by monchin** [comment]
> Dear @monchin,
> Before going into any reproducible examples etc, I have to ask: have you specifically included the mass cytometry parameters that you are interested in, and added it in a matrix/dataframe format, with the parameters as columns and the observations as rows? It could be that this is caused by inclusion of a time parameter, or something else that is not in integer or float format. You should only include the parameters that contain some meaningful information that you think will separate the data, in most instances only the channels with protein abundance information. It seems correct with the transformation. With asinh you should use a co-factor of something like 5 with mass cytometry data, if I am not mistaken.
> Best regards
> Jakob

Dear @jtheorell 
Thank you for your reply. I have exluded all the features I don't need in analysis. I changed it into a `.csv` file.
It seems that because I'm not familiar with R, when I got the file in, it generated a index column automatically. I'll try to get index out and try again.

**Comment by monchin** [comment]
After  I  get index column out, all things go well. Thank you for your patience.

**Comment by jtheorell** [comment]
Oh, that is a classical thing. Happy you found the problem.
